import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Student Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section className="text-gray-600 body-font">
          <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
            <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 mb-10 md:mb-0">
              <Image
                className="object-cover object-center rounded"
                alt="hero"
                src="/stock-image.jpg"
                height="600"
                width="720"
              />
            </div>
            <div className="lg:flex-grow md:w-1/2 lg:pl-24 md:pl-16 flex flex-col md:items-start md:text-left items-center text-center">
              <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                Time Table Planner
              </h1>
              <p className="mb-8 leading-relaxed">
                A single place to plan / draft / manage your classes. Create
                your timetable and have a look at the calendar and see all your
                scheduled classes in one place. You can also unenroll in the
                courses you don't like.
              </p>
              <div className="flex justify-center">
                <Link href="/register">
                  <a className="inline-flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-red-600 rounded text-lg">
                    Register
                  </a>
                </Link>
                <Link href="/login">
                  <a className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
                    Login
                  </a>
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
